export interface ImportedArticle {
  id: string; slug: string; title: string; excerpt: string; coverImage: string; date: string; author: string; readTime: string; tags: string[]; googleDocId: string;
}

export const importedArticles: ImportedArticle[] = [
  {"id": "101", "slug": "kitchen-installer-services-jeddah", "title": "فني تركيب مطابخ 0567659475 لفك وتجديد وتركيب المطابخ", "excerpt": "فني تركيب مطابخ متخصص في جدة لتركيب وصيانة المطابخ الألمنيوم والخشب والرخام بدقة واحتراف، مع خدمة معاينة وتجهيز متكاملة", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["فني تركيب مطابخ", "تركيب مطابخ ألمنيوم", "فني تركيب مطابخ بالقصيم", "فني تركيب مطابخ حي الجامعه بجده"], "googleDocId": "1hx1hkYUq0Ect6SUisjZ-bqpxDQrxaUv2qZBd87_NyWg"},
  {"id": "102", "slug": "kitchen-installer-jeddah", "title": "فني تركيب مطابخ جدة: اتصل 0567659475 لخدمات متكاملة", "excerpt": "فني تركيب مطابخ جدة بخبرة في تركيب وتثبيت المطابخ بمختلف الخامات، مع ضبط الخزائن والأدراج والأبواب بدقة وتنفيذ الخدمة وفق المقاسات والتصميم", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "7 دقائق", "tags": ["فني تركيب مطابخ جدة", "فني تركيب مطابخ جدة الجامعة", "معلم تركيب مطابخ", "فني مطابخ ألمنيوم في جدة"], "googleDocId": "13eF3FM30vt8d2AmO0w0Ikvh0uHdQenVWWT7xGIh7AEI"},
  {"id": "103", "slug": "kitchen-moving-installation-jeddah", "title": "نقل وتركيب مطابخ جدة 567659475 اتصل بمتخصص في النقل", "excerpt": "نقل وتركيب مطابخ باحترافية في جدة، مع فك آمن ونقل منظم وإعادة تركيب دقيقة لمختلف أنواع المطابخ، مع ضبط الخزائن والأبواب والتوصيلات", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "7 دقائق", "tags": ["نقل وتركيب مطابخ", "اسعار نقل وتركيب مطابخ جده", "معلم تركيب مطابخ جدة", "تركيب مطابخ ألمنيوم", "تركيب مطبخ جاهز"], "googleDocId": "1dkXYLg1P3dXtVU2uLzJqNMgryMa3F-g1Dw_kSkMPq0Q"},
  {"id": "104", "slug": "aluminum-kitchen-maintenance-technician", "title": "فني صيانة مطابخ ألمنيوم 0567659475 لاكتشاف العطل مبكرا", "excerpt": "فني صيانة مطابخ ألمنيوم لإصلاح الأبواب والأدراج والمفصلات، وضبط الوحدات ومعالجة الأعطال بدقة، مع خدمات تركيب وتعديل المطابخ في جدة", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["فني صيانة مطابخ ألمنيوم", "تركيب مطابخ ألمنيوم"], "googleDocId": "1N1B0qUHuvV_gfwBFunSYljfNWhFI0fvB4enWou4R9ug"},
  {"id": "105", "slug": "kitchen-disassembly-reinstallation", "title": "فك وتركيب مطابخ 0567659475 خبرة في التعامل مع التوصيلات", "excerpt": "خدمة فك وتركيب مطابخ باحترافية ودقة، تشمل فك الخزائن ونقلها وإعادة تركيبها وضبط الأبواب والأدراج، مع تنفيذ منظم يحافظ على المكونات", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "7 دقائق", "tags": ["فك وتركيب مطابخ", "ارقام معلم فك وتركيب مطابخ", "طريقة فك وتركيب المطابخ", "فني فك وتركيب مطابخ", "عامل تركيب مطابخ"], "googleDocId": "1Aw53VTrb_0Mqan5GBCyujfQwN68NlO1OYnNIsgpjW9k"},
  {"id": "106", "slug": "kitchen-hinge-repair", "title": "تصليح مفصلات المطبخ 0567659475 والتخلص من التلفيات", "excerpt": "تصليح مفصلات المطبخ باحترافية لإصلاح الأعطال وضبط الأبواب والمفصلات الهيدروليكية والسوفت كلوز، مع خدمة دقيقة وسريعة تناسب مختلف المطابخ", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "5 دقائق", "tags": ["تصليح مفصلات المطبخ", "طريقة تركيب مفصلات المطبخ", "مفصلات مطابخ سوفت كلوز", "إصلاح ذراع هيدروليك مطابخ", "مفصلات مطابخ هيدروليك"], "googleDocId": "1tSI8H4_UNbGhNs81MIq-yR3Dwx9dQZNfe7TlDk55zE0"},
  {"id": "107", "slug": "kitchen-installation-master-jeddah", "title": "معلم تركيب مطابخ جده 0567659475 دقة واحترافية وجودة", "excerpt": "معلم تركيب مطابخ جده يقدم خدمات تركيب ونقل وصيانة المطابخ بدقة، مع ضبط الخزائن والأدراج والمفصلات وتنفيذ العمل باحترافية", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["معلم تركيب مطابخ جده", "نقل وتركيب مطابخ", "فني صيانة مطابخ المنيوم"], "googleDocId": "1tw5_2KfZtZf3fTyMjqEm0YAGlly4IZa48NRIx4y-8tE"},
  {"id": "108", "slug": "aluminum-kitchen-technician-jeddah", "title": "فني مطابخ ألمنيوم في جدة 0567659475 لمظهر أنيق", "excerpt": "فني مطابخ ألمنيوم في جدة لتركيب وصيانة وتعديل المطابخ بدقة، مع إصلاح الأبواب والأدراج والمفصلات وتنفيذ حلول مناسبة لمختلف المساحات", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "7 دقائق", "tags": ["فني مطابخ ألمنيوم في جدة", "فني صيانة مطابخ ألمنيوم", "تركيب مطابخ ألمنيوم", "فني مطابخ حي الصفا"], "googleDocId": "10vit3rRQwUcoVV3jdrHCmHUSobcoad0oW8S8nciieJc"},
  {"id": "109", "slug": "kitchen-technician-al-safa-jeddah", "title": "فني مطابخ حي الصفا 0567659475 لخدمات التركيب والصيانة", "excerpt": "فني مطابخ حي الصفا يقدم خدمات تركيب وفك ونقل وصيانة المطابخ بدقة، مع معاينة وتجهيز احترافي وحلول مناسبة لمختلف التصاميم والمساحات", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["فني مطابخ حي الصفا", "فني مطابخ جدة رخيصة", "معلم تركيب مطابخ", "نقل وتركيب مطابخ"], "googleDocId": "1xza1V-ysDzwC2qQPvC8T8beHVLmELBE46dhlxlNBX0w"},
  {"id": "110", "slug": "ready-made-kitchen-installation", "title": "تركيب مطبخ جاهز 0567659475 جهز مطبخك في الوقت المناسب", "excerpt": "تركيب مطبخ جاهز باحترافية في جدة مع فنيين متخصصين، لضمان تثبيت الخزائن والوحدات بدقة وتنظيم المساحة وفق التصميم والمقاسات", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["تركيب مطبخ جاهز", "عامل تركيب مطابخ", "تركيب مطابخ ألمنيوم"], "googleDocId": "1Q7m0UrxgbKxQQy4cbQrkzIy70j7ajGrDkWHP-ID4cNw"},
  {"id": "111", "slug": "kitchen-installation-worker-jeddah", "title": "عامل تركيب مطابخ في جدة 0567659475 اتصل الآن", "excerpt": "عامل تركيب مطابخ في جدة لتركيب وفك ونقل المطابخ بدقة، مع خدمات تركيب مطابخ الألمنيوم وضبط الخزائن والأبواب والأدراج باحترافية وجودة عالية", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["عامل تركيب مطابخ", "معلم تركيب مطابخ جدة", "تركيب مطابخ ألمنيوم", "فني مطابخ ألمنيوم", "نقل وتركيب مطابخ"], "googleDocId": "187mxfRYaMGjyC1OXvo6NiEUro-57X2cktaMUamr1nro"},
  {"id": "112", "slug": "ikea-kitchen-customization-jeddah", "title": "تفصيل مطبخ ايكيا 0567659475 تصميم عملي ومظهر عصري", "excerpt": "تفصيل مطبخ ايكيا بتصميم عملي يناسب مساحتك، مع اختيار الوحدات والإكسسوارات وتركيب دقيق لتحقيق أفضل استغلال للمساحة ومظهر عصري", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "7 دقائق", "tags": ["تفصيل مطبخ ايكيا", "تفصيل مطابخ ايكيا", "تفصيل مطبخ من ايكيا", "كم يكلف تفصيل مطبخ من ايكيا", "موقع تفصيل مطبخ ايكيا"], "googleDocId": "1ae0PEHqKfWSls3pZnB-nxEBynez5VwR3Lof_bvBdhp4"},
  {"id": "113", "slug": "custom-kitchen-marble-jeddah", "title": "تفصيل رخام مطابخ 0567659475 تصاميم تجمع بين الفخامة والعملية", "excerpt": "تفصيل رخام مطابخ بتصاميم عصرية ومقاسات دقيقة تناسب مختلف المساحات، مع تنفيذ احترافي واختيار أفضل الخامات لتوفير مطبخ أنيق وعملي", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "7 دقائق", "tags": ["تفصيل رخام مطابخ", "مطابخ تفصيل جدة", "مطابخ رخام حديثة", "مطابخ رخام وجرانيت", "مطابخ رخام كاملة"], "googleDocId": "1COp6Pv2Qc3yLfEGYvRxytCaUvsCmZUDj-Zih7R-Rrzg"},
  {"id": "114", "slug": "best-custom-kitchen-shop-jeddah", "title": "افضل محل تفصيل مطابخ في جدة 0567659475 تصاميم عصرية", "excerpt": "افضل محل تفصيل مطابخ في جدة بتصاميم عصرية وخامات متنوعة، مع تنفيذ دقيق يناسب مختلف المساحات وتقديم حلول عملية بأسعار مناسبة", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["افضل محل تفصيل مطابخ", "أفضل محل تفصيل مطابخ في جدة بسعر رخيص", "تفصيل مطبخ رخيص", "تفصيل مطابخ ألمنيوم"], "googleDocId": "1MAtsrclAUdM6oP6LpRwPicuwvJv7Uhf5GLcONnx4zN8"},
  {"id": "115", "slug": "cheap-custom-kitchens-jeddah", "title": "تفصيل مطابخ بجدة رخيصه 0567659475 خيارات عملية بتكلفة مناسبة وجودة جيدة", "excerpt": "تفصيل مطابخ بجدة رخيصه بتصاميم عملية وخامات متنوعة تناسب مختلف المساحات والميزانيات، مع خدمة قياس وتصميم وتركيب مطابخ حسب الطلب", "coverImage": "https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4349d4a5-ce5a-49ef-b247-e8bf955ca42b", "date": "2026-09-28", "author": "هند", "readTime": "6 دقائق", "tags": ["تفصيل مطابخ بجدة رخيصه", "اماكن تفصيل مطابخ رخيصه بجده", "أفضل محلات المطابخ في جدة", "تفصيل مطابخ الحمدانية"], "googleDocId": "1iIR90XdCx0dPabZel8rZ8fTEJ-GZPFCcP8XG2u6P6wk"},
];

export const getImportedArticle = (slug: string) => importedArticles.find((article) => article.slug === slug);
